FROM python:3.8

# python envs
ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

RUN apt-get update -y
RUN apt-get install binutils libproj-dev gdal-bin cron -y

COPY ./conf/requirements.txt /
RUN /usr/local/bin/python -m pip install --upgrade pip && pip install -r ./requirements.txt

WORKDIR /opt/
EXPOSE 8000